export interface Item {
	'ad': number,
	'ad_mult': { 'type': string, 'value': number; },
	'allowed_to': { 'melee': boolean, 'ranged': boolean; },
	'ap': number,
	'ap_mult': { 'type': string, 'value': number; },
	'apen%': number,
	'apiname': string,
	'arm': number,
	'as': number,
	'att_m_proc': number,
	'att_phys_proc': number,
	'boots_ms': number,
	'cdr': number,
	'crit': number,
	'critdmg': number,
	'flat_ms': number,
	'gold': number,
	'heal_shield': number,
	'hp': number,
	'hp5': number,
	'hp5%': number,
	'hp_mult': { 'type': string, 'value': number; },
	'img': string,
	'index': number,
	'leth': number,
	'ls': number,
	'magic_on_hit': number,
	'modes': string,
	'mp': number,
	'mp5': number,
	'mp5%': number,
	'mpen': number,
	'mpen%': number,
	'mr': number,
	'ms%': number,
	'name': string,
	'phys_on_hit': number,
	'shared_item': any,
	'shared_passives': any,
	'shield': number,
	'spell_m_proc': any, // type string is not assignable to number?
	'spell_vamp': number,
	'stacked': boolean,
	'stackable': any,
	'tags': string,
	'tenacity': number,
	'visible': boolean,
}

export interface ItemRestrictions {
	"hasGoldOrJg": boolean,
	"hasBoots": boolean,
	"hasTear": boolean,
	"masterworkItems": [Item, Item],
	"hasHexcore": boolean;
}