export interface Item {
	'ability_haste'?: number,
	'ad'?: number,
	'ad_mult'?: { 'type': string, 'value': number; },
	'allowed_to': { 'melee': boolean, 'ranged': boolean; },
	'ap'?: number,
	'ap_mult'?: { 'type': string, 'value': number, },
	'apen%'?: number,
	'apiname': string,
	'arm'?: number,
	'as'?: number,
	'att_m_proc'?: number,
	'att_phys_proc'?: number,
	'boots_ms'?: number,
	'cdr'?: number,
	'crit'?: number,
	'critdmg'?: number,
	'gold': number,
	'heal_shield'?: number,
	'hp'?: number,
	'hp5'?: number,
	'hp5%'?: number,
	'hp_mult'?: { 'type': string, 'value': number; },
	'id': string,
	'img': string,
	'index': number,
	'leth'?: number,
	'ls'?: number,
	'magic_on_hit'?: number,
	'mp'?: number,
	'mp5'?: number,
	'mp5%'?: number,
	'mpen'?: number,
	'mpen%'?: number,
	'mr'?: number,
	'ms'?: number,
	'ms%'?: number,
	'name': string,
	'passives'?: any,
	'phys_on_hit'?: number,
	'rank'?: string,
	'shared_item'?: any,
	'shared_passives'?: any,
	'shield'?: number,
	'spell_m_proc'?: any, // type string is not assignable to number?
	'spell_vamp'?: number,
	'stacked'?: boolean,
	'stackable'?: any,
	'tags': string,
	'tenacity'?: number,
	'tooltip'?: string,
	'visible': boolean,
}

export const EMPTY_ITEM: Item = {
	'ability_haste': 0,
	'ad': 0,
	'allowed_to': { 'melee': true, 'ranged': true },
	'ap': 0,
	'apen%': 0,
	'apiname': '',
	'arm': 0,
	'as': 0,
	'att_m_proc': 0,
	'att_phys_proc': 0,
	'boots_ms': 0,
	// 'cdr': 0,
	'crit': 0,
	'critdmg': 0,
	'gold': 0,
	'heal_shield': 0,
	'hp': 0,
	'hp5': 0,
	'hp5%': 0,
	'id': '0000',
	'img': '',
	'index': 0,
	'leth': 0,
	'ls': 0,
	'magic_on_hit': 0,
	'mp': 0,
	'mp5': 0,
	'mp5%': 0,
	'mpen': 0,
	'mpen%': 0,
	'mr': 0,
	'ms': 0,
	'ms%': 0,
	'name': 'Empty',
	'phys_on_hit': 0,
	'rank': '',
	'shared_item': null,
	'shared_passives': [],
	'shield': 0,
	'spell_m_proc': 0,
	'stackable': false,
	'stacked': false,
	'tags': '',
	'tenacity': 0,
	'visible': true,
};

export interface ItemRestrictions {
	"hasGoldOrJg": boolean,
	"hasBoots": boolean,
	"hasTear": boolean,
	"masterworkItems": [Item, Item],
	"hasHexcore": boolean;
}