export const RUNES = [{
	"runes":
		[{
			"keystones": [{
				"name": "Press the Attack",
				"img": "assets/images/runes/Precision/Press the Attack.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Lethal Tempo",
				"img": "assets/images/runes/Precision/Lethal Tempo.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Fleet Footwork",
				"img": "assets/images/runes/Precision/Fleet Footwork.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Conqueror",
				"img": "assets/images/runes/Precision/Conqueror.png",
				"active": false,
				"keyslot": "keystones",
			}],
			"slot1": [{
				"name": "Overheal",
				"img": "assets/images/runes/Precision/Overheal.png",
				"active": false,
				"keyslot": "slot1",
				"index": 0,
			},
			{
				"name": "Triumph",
				"img": "assets/images/runes/Precision/Triumph.png",
				"active": false,
				"keyslot": "slot1",
				"index": 1,
			},
			{
				"name": "Presence of Mind",
				"img": "assets/images/runes/Precision/Presence of Mind.png",
				"active": false,
				"keyslot": "slot1",
				"index": 2,
			}],
			"slot2": [{
				"name": "Legend: Alacrity",
				"img": "assets/images/runes/Precision/Legend Alacrity.png",
				"active": false,
				"keyslot": "slot2",
				"index": 0,
			},
			{
				"name": "Legend: Tenacity",
				"img": "assets/images/runes/Precision/Legend Tenacity.png",
				"active": false,
				"keyslot": "slot2",
				"index": 1,
			},
			{
				"name": "Legend: Bloodline",
				"img": "assets/images/runes/Precision/Legend Bloodline.png",
				"active": false,
				"keyslot": "slot2",
				"index": 2,
			}],
			"slot3": [{
				"name": "Coup de Grace",
				"img": "assets/images/runes/Precision/Coup de Grace.png",
				"active": false,
				"keyslot": "slot3",
				"index": 0,
			},
			{
				"name": "Cut Down",
				"img": "assets/images/runes/Precision/Cut Down.png",
				"active": false,
				"keyslot": "slot3",
				"index": 1,
			},
			{
				"name": "Last Stand",
				"img": "assets/images/runes/Precision/Last Stand.png",
				"active": false,
				"keyslot": "slot3",
				"index": 2,
			}],
		}],
	"path_name": "Precision",
	"img": "assets/images/runes/Precision/Precision.png",
	"active_primary": false,
	"active_secondary": false,
}, {
	"runes": [{
		"keystones": [
			{
				"name": "Electrocute",
				"img": "assets/images/runes/Domination/Electrocute.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Predator",
				"img": "assets/images/runes/Domination/Predator.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Dark Harvest",
				"img": "assets/images/runes/Domination/Dark Harvest.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Hail of Blades",
				"img": "assets/images/runes/Domination/Hail of Blades.png",
				"active": false,
				"keyslot": "keystones",
			}],
		"slot1": [{
			"name": "Cheap Shot",
			"img": "assets/images/runes/Domination/Cheap Shot.png",
			"active": false,
			"keyslot": "slot1",
			"index": 0,
		},
		{
			"name": "Taste of Blood",
			"img": "assets/images/runes/Domination/Taste of Blood.png",
			"active": false,
			"keyslot": "slot1",
			"index": 1,
		},
		{
			"name": "Sudden Impact",
			"img": "assets/images/runes/Domination/Sudden Impact.png",
			"active": false,
			"keyslot": "slot1",
			"index": 2,
		}],
		"slot2": [{
			"name": "Zombie Ward",
			"img": "assets/images/runes/Domination/Zombie Ward.png",
			"active": false,
			"keyslot": "slot2",
			"index": 0,
		},
		{
			"name": "Ghost Poro",
			"img": "assets/images/runes/Domination/Ghost Poro.png",
			"active": false,
			"keyslot": "slot2",
			"index": 1,
		},
		{
			"name": "Eyeball Collection",
			"img": "assets/images/runes/Domination/Eyeball Collection.png",
			"active": false,
			"keyslot": "slot2",
			"index": 2,
		}],
		"slot3": [{
			"name": "Ravenous Hunter",
			"img": "assets/images/runes/Domination/Ravenous Hunter.png",
			"active": false,
			"keyslot": "slot3",
			"index": 0,
		},
		{
			"name": "Ingenious Hunter",
			"img": "assets/images/runes/Domination/Ingenious Hunter.png",
			"active": false,
			"keyslot": "slot3",
			"index": 1,
		},
		{
			"name": "Relentless Hunter",
			"img": "assets/images/runes/Domination/Relentless Hunter.png",
			"active": false,
			"keyslot": "slot3",
			"index": 2,
		},
		{
			"name": "Ultimate Hunter",
			"img": "assets/images/runes/Domination/Ultimate Hunter.png",
			"active": false,
			"keyslot": "slot3",
			"index": 3,
		}],

	}],
	"path_name": "Domination",
	"img": "assets/images/runes/Domination/Domination.png",
	"active_primary": false,
	"active_secondary": false,
}, {
	"runes": [{
		"keystones": [
			{
				"name": "Summon Aery",
				"img": "assets/images/runes/Sorcery/Summon Aery.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Arcane Comet",
				"img": "assets/images/runes/Sorcery/Arcane Comet.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Phase Rush",
				"img": "assets/images/runes/Sorcery/Phase Rush.png",
				"active": false,
				"keyslot": "keystones",
			}],
		"slot1": [{
			"name": "Nullifying Orb",
			"img": "assets/images/runes/Sorcery/Nullifying Orb.png",
			"active": false,
			"keyslot": "slot1",
			"index": 0,
		},
		{
			"name": "Manaflow Band",
			"img": "assets/images/runes/Sorcery/Manaflow Band.png",
			"active": false,
			"keyslot": "slot1",
			"index": 1,
		},
		{
			"name": "Nimbus Cloak",
			"img": "assets/images/runes/Sorcery/Nimbus Cloak.png",
			"active": false,
			"keyslot": "slot1",
			"index": 2,
		}],
		"slot2": [{
			"name": "Transcendence",
			"img": "assets/images/runes/Sorcery/Transcendence.png",
			"active": false,
			"keyslot": "slot2",
			"index": 0,
		},
		{
			"name": "Celerity",
			"img": "assets/images/runes/Sorcery/Celerity.png",
			"active": false,
			"keyslot": "slot2",
			"index": 1,
		},
		{
			"name": "Absolute Focus",
			"img": "assets/images/runes/Sorcery/Absolute Focus.png",
			"active": false,
			"keyslot": "slot2",
			"index": 2,
		}],
		"slot3": [{
			"name": "Scorch",
			"img": "assets/images/runes/Sorcery/Scorch.png",
			"active": false,
			"keyslot": "slot3",
			"index": 0,
		},
		{
			"name": "Waterwalking",
			"img": "assets/images/runes/Sorcery/Waterwalking.png",
			"active": false,
			"keyslot": "slot3",
			"index": 1,
		},
		{
			"name": "Gathering Storm",
			"img": "assets/images/runes/Sorcery/Gathering Storm.png",
			"active": false,
			"keyslot": "slot3",
			"index": 2
		}],

	}],
	"path_name": "Sorcery",
	"img": "assets/images/runes/Sorcery/Sorcery.png",
	"active_primary": false,
	"active_secondary": false,
}, {
	"runes": [{
		"keystones": [
			{
				"name": "Grasp of the Undying",
				"img": "assets/images/runes/Resolve/Grasp of the Undying.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Aftershock",
				"img": "assets/images/runes/Resolve/Aftershock.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Guardian",
				"img": "assets/images/runes/Resolve/Guardian.png",
				"active": false,
				"keyslot": "keystones",
			},],
		"slot1": [{
			"name": "Demolish",
			"img": "assets/images/runes/Resolve/Demolish.png",
			"active": false,
			"keyslot": "slot1",
			"index": 0,
		},
		{
			"name": "Font of Life",
			"img": "assets/images/runes/Resolve/Font of Life.png",
			"active": false,
			"keyslot": "slot1",
			"index": 1,
		},
		{
			"name": "Shield Bash",
			"img": "assets/images/runes/Resolve/Shield Bash.png",
			"active": false,
			"keyslot": "slot1",
			"index": 2,
		}],
		"slot2": [{
			"name": "Conditioning",
			"img": "assets/images/runes/Resolve/Conditioning.png",
			"active": false,
			"keyslot": "slot2",
			"index": 0,
		},
		{
			"name": "Second Wind",
			"img": "assets/images/runes/Resolve/Second Wind.png",
			"active": false,
			"keyslot": "slot2",
			"index": 1,
		},
		{
			"name": "Bone Plating",
			"img": "assets/images/runes/Resolve/Bone Plating.png",
			"active": false,
			"keyslot": "slot2",
			"index": 2,
		}],
		"slot3": [{
			"name": "Overgrowth",
			"img": "assets/images/runes/Resolve/Overgrowth.png",
			"active": false,
			"keyslot": "slot3",
			"index": 0,
		},
		{
			"name": "Revitalize",
			"img": "assets/images/runes/Resolve/Revitalize.png",
			"active": false,
			"keyslot": "slot3",
			"index": 1,
		},
		{
			"name": "Unflinching",
			"img": "assets/images/runes/Resolve/Unflinching.png",
			"active": false,
			"keyslot": "slot3",
			"index": 2,
		}],

	}],
	"path_name": "Resolve",
	"img": "assets/images/runes/Resolve/Resolve.png",
	"active_primary": false,
	"active_secondary": false,
}, {
	"runes": [{
		"keystones": [
			{
				"name": "Glacial Augment",
				"img": "assets/images/runes/Inspiration/Glacial Augment.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Unsealed Spellbook",
				"img": "assets/images/runes/Inspiration/Unsealed Spellbook.png",
				"active": false,
				"keyslot": "keystones",
			},
			{
				"name": "Prototype: Omnistone",
				"img": "assets/images/runes/Inspiration/Prototype Omnistone.png",
				"active": false,
				"keyslot": "keystones",
			},],
		"slot1": [{
			"name": "Hextech Flashtraption",
			"img": "assets/images/runes/Inspiration/Hextech Flashtraption.png",
			"active": false,
			"keyslot": "slot1",
			"index": 0,
		},
		{
			"name": "Magical Footwear",
			"img": "assets/images/runes/Inspiration/Magical Footwear.png",
			"active": false,
			"keyslot": "slot1",
			"index": 1,
		},
		{
			"name": "Perfect Timing",
			"img": "assets/images/runes/Inspiration/Perfect Timing.png",
			"active": false,
			"keyslot": "slot1",
			"index": 2,
		}],
		"slot2": [{
			"name": "Future's Market",
			"img": "assets/images/runes/Inspiration/Future's Market.png",
			"active": false,
			"keyslot": "slot2",
			"index": 0,
		},
		{
			"name": "Minion Dematerializer",
			"img": "assets/images/runes/Inspiration/Minion Dematerializer.png",
			"active": false,
			"keyslot": "slot2",
			"index": 1,
		},
		{
			"name": "Biscuit Delivery",
			"img": "assets/images/runes/Inspiration/Biscuit Delivery.png",
			"active": false,
			"keyslot": "slot2",
			"index": 2,
		}],
		"slot3": [{
			"name": "Cosmic Insight",
			"img": "assets/images/runes/Inspiration/Cosmic Insight.png",
			"active": false,
			"keyslot": "slot3",
			"index": 0,
		},
		{
			"name": "Approach Velocity",
			"img": "assets/images/runes/Inspiration/Approach Velocity.png",
			"active": false,
			"keyslot": "slot3",
			"index": 1,
		},
		{
			"name": "Time Warp Tonic",
			"img": "assets/images/runes/Inspiration/Time Warp Tonic.png",
			"active": false,
			"keyslot": "slot3",
			"index": 2,
		}],

	}],
	"path_name": "Inspiration",
	"img": "assets/images/runes/Inspiration/Inspiration.png",
	"active_primary": false,
	"active_secondary": false,
}]